/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PollTokenRouteImport } from './routes/poll.$token'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecureBoxRouteImport } from './routes/_authenticated/secure-box'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedPlanOperationRouteImport } from './routes/_authenticated/plan-operation'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedMeetingActionsRouteImport } from './routes/_authenticated/meeting-actions'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiGoogleCalendarCallbackRouteImport } from './routes/api/google-calendar/callback'
import { Route as ApiPublicHooksRsvpRemindersRouteImport } from './routes/api/public/hooks/rsvp-reminders'
import { Route as ApiPublicPollTokenFilesRouteImport } from './routes/api/public/poll/$token/files'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollTokenRoute = PollTokenRouteImport.update({
  id: '/poll/$token',
  path: '/poll/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecureBoxRoute = AuthenticatedSecureBoxRouteImport.update({
  id: '/secure-box',
  path: '/secure-box',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanOperationRoute =
  AuthenticatedPlanOperationRouteImport.update({
    id: '/plan-operation',
    path: '/plan-operation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingActionsRoute =
  AuthenticatedMeetingActionsRouteImport.update({
    id: '/meeting-actions',
    path: '/meeting-actions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiGoogleCalendarCallbackRoute =
  ApiGoogleCalendarCallbackRouteImport.update({
    id: '/api/google-calendar/callback',
    path: '/api/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRsvpRemindersRoute =
  ApiPublicHooksRsvpRemindersRouteImport.update({
    id: '/api/public/hooks/rsvp-reminders',
    path: '/api/public/hooks/rsvp-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPollTokenFilesRoute = ApiPublicPollTokenFilesRouteImport.update({
  id: '/api/public/poll/$token/files',
  path: '/api/public/poll/$token/files',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/meeting-actions': typeof AuthenticatedMeetingActionsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan-operation': typeof AuthenticatedPlanOperationRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/search': typeof AuthenticatedSearchRoute
  '/secure-box': typeof AuthenticatedSecureBoxRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/poll/$token': typeof PollTokenRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/public/hooks/rsvp-reminders': typeof ApiPublicHooksRsvpRemindersRoute
  '/api/public/poll/$token/files': typeof ApiPublicPollTokenFilesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/meeting-actions': typeof AuthenticatedMeetingActionsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan-operation': typeof AuthenticatedPlanOperationRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/search': typeof AuthenticatedSearchRoute
  '/secure-box': typeof AuthenticatedSecureBoxRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/poll/$token': typeof PollTokenRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/public/hooks/rsvp-reminders': typeof ApiPublicHooksRsvpRemindersRoute
  '/api/public/poll/$token/files': typeof ApiPublicPollTokenFilesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/meeting-actions': typeof AuthenticatedMeetingActionsRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/plan-operation': typeof AuthenticatedPlanOperationRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/secure-box': typeof AuthenticatedSecureBoxRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/poll/$token': typeof PollTokenRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/public/hooks/rsvp-reminders': typeof ApiPublicHooksRsvpRemindersRoute
  '/api/public/poll/$token/files': typeof ApiPublicPollTokenFilesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/admin'
    | '/calendar'
    | '/contacts'
    | '/dashboard'
    | '/documents'
    | '/inbox'
    | '/meeting-actions'
    | '/meetings'
    | '/onboarding'
    | '/plan-operation'
    | '/roadmap'
    | '/search'
    | '/secure-box'
    | '/settings'
    | '/stats'
    | '/tasks'
    | '/poll/$token'
    | '/api/google-calendar/callback'
    | '/api/public/hooks/rsvp-reminders'
    | '/api/public/poll/$token/files'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/admin'
    | '/calendar'
    | '/contacts'
    | '/dashboard'
    | '/documents'
    | '/inbox'
    | '/meeting-actions'
    | '/meetings'
    | '/onboarding'
    | '/plan-operation'
    | '/roadmap'
    | '/search'
    | '/secure-box'
    | '/settings'
    | '/stats'
    | '/tasks'
    | '/poll/$token'
    | '/api/google-calendar/callback'
    | '/api/public/hooks/rsvp-reminders'
    | '/api/public/poll/$token/files'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/inbox'
    | '/_authenticated/meeting-actions'
    | '/_authenticated/meetings'
    | '/_authenticated/onboarding'
    | '/_authenticated/plan-operation'
    | '/_authenticated/roadmap'
    | '/_authenticated/search'
    | '/_authenticated/secure-box'
    | '/_authenticated/settings'
    | '/_authenticated/stats'
    | '/_authenticated/tasks'
    | '/poll/$token'
    | '/api/google-calendar/callback'
    | '/api/public/hooks/rsvp-reminders'
    | '/api/public/poll/$token/files'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PollTokenRoute: typeof PollTokenRoute
  ApiGoogleCalendarCallbackRoute: typeof ApiGoogleCalendarCallbackRoute
  ApiPublicHooksRsvpRemindersRoute: typeof ApiPublicHooksRsvpRemindersRoute
  ApiPublicPollTokenFilesRoute: typeof ApiPublicPollTokenFilesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$token': {
      id: '/poll/$token'
      path: '/poll/$token'
      fullPath: '/poll/$token'
      preLoaderRoute: typeof PollTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secure-box': {
      id: '/_authenticated/secure-box'
      path: '/secure-box'
      fullPath: '/secure-box'
      preLoaderRoute: typeof AuthenticatedSecureBoxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan-operation': {
      id: '/_authenticated/plan-operation'
      path: '/plan-operation'
      fullPath: '/plan-operation'
      preLoaderRoute: typeof AuthenticatedPlanOperationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meeting-actions': {
      id: '/_authenticated/meeting-actions'
      path: '/meeting-actions'
      fullPath: '/meeting-actions'
      preLoaderRoute: typeof AuthenticatedMeetingActionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/google-calendar/callback': {
      id: '/api/google-calendar/callback'
      path: '/api/google-calendar/callback'
      fullPath: '/api/google-calendar/callback'
      preLoaderRoute: typeof ApiGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rsvp-reminders': {
      id: '/api/public/hooks/rsvp-reminders'
      path: '/api/public/hooks/rsvp-reminders'
      fullPath: '/api/public/hooks/rsvp-reminders'
      preLoaderRoute: typeof ApiPublicHooksRsvpRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poll/$token/files': {
      id: '/api/public/poll/$token/files'
      path: '/api/public/poll/$token/files'
      fullPath: '/api/public/poll/$token/files'
      preLoaderRoute: typeof ApiPublicPollTokenFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMeetingActionsRoute: typeof AuthenticatedMeetingActionsRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanOperationRoute: typeof AuthenticatedPlanOperationRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSecureBoxRoute: typeof AuthenticatedSecureBoxRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMeetingActionsRoute: AuthenticatedMeetingActionsRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanOperationRoute: AuthenticatedPlanOperationRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSecureBoxRoute: AuthenticatedSecureBoxRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PollTokenRoute: PollTokenRoute,
  ApiGoogleCalendarCallbackRoute: ApiGoogleCalendarCallbackRoute,
  ApiPublicHooksRsvpRemindersRoute: ApiPublicHooksRsvpRemindersRoute,
  ApiPublicPollTokenFilesRoute: ApiPublicPollTokenFilesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
